

#hello world printing with github actions
name: Hello world

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}      
          
      - name: Run web server container for 10 minutes
        run: |
          docker run -d --name web-server -p 8080:8000 python:3 python -m http.server 8000
          sleep 600  # Wait for 10 minutes
          docker stop web-server


